django/app_chat/urls.py
from django.urls import path
from . import views


app_name = "app_chat"
urlpatterns = [path("<str:matched_user_name>", views.chat_with_match, name="chat")]

django/app_home/urls.py
from django.urls import path
from . import views

app_name = "app_home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("swipe/", views.SwipeView.as_view(), name="swipe"),
]

django/app_users/urls.py
from django.urls import path
from . import views

app_name = "app_users"
urlpatterns = [
    path("signup/", views.UserSignUp.as_view(), name="user-signup"),
    path(
        "profile/details/",
        views.UserProfileDetails.as_view(),
        name="user-profile-details",
    ),
    path(
        "profile/update/",
        views.UserProfileUpdate.as_view(),
        name="user-profile-update",
    ),
    path(
        "profile/delete/",
        views.UserProfileDelete.as_view(),
        name="user-profile-delete",
    ),
    path(
        "profile/picture/",
        views.UserProfilePictureUpdate.as_view(),
        name="user-profile-picture",
    ),
    path(
        "profile/matches/",
        views.UserMatches.as_view(),
        name="user-matches",
    ),
    path(
        "match/details/<str:username>/",
        views.UserMatchProfileDetails.as_view(),
        name="user-match-profile-details",
    ),
    path(
        "match/delete/<str:username>/",
        views.UserMatchDelete.as_view(),
        name="user-match-delete",
    ),
    path(
        "sock/overview/",
        views.SockProfileOverview.as_view(),
        name="sock-overview",
    ),
    path(
        "sock/select/",
        views.SockSelection.as_view(),
        name="sock-selection",
    ),
    path(
        "sock/details/",
        views.SockProfileDetails.as_view(),
        name="sock-details",
    ),
    path(
        "sock/create/",
        views.SockProfileCreate.as_view(),
        name="sock-create",
    ),
    path(
        "sock/update/",
        views.SockProfileUpdate.as_view(),
        name="sock-update",
    ),
    path(
        "sock/picture/",
        views.SockProfilePictureUpdate.as_view(),
        name="sock-picture",
    ),
]

django/hotsox_project/urls.py
import os
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    # Main Home route
    path("", include("app_home.urls")),
    # User Authentication
    path("user/", include("app_users.urls")),
    path("user/", include("allauth.urls")),
    path("chat/", include("app_chat.urls")),
    # API Routes
    path(os.environ.get("DRFAPI_URL", "api/v1") + "/", include("app_restapi.urls")),
    # path('api/auth/', include('rest_framework.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_URL)

django/templates/base.html
{% load django_simple_cookie_consent_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap_quartz.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% display_cookie_consent %}
    <title>{% block title %} Hotsox {% endblock %}</title>
</head>

<body>
    <!--Nav-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-cardlike">
        <div class="container-fluid">
            <a href="{% url 'app_home:index' %}" class="navbar-brand">
                HotSox
            </a>
            <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav me-auto">
                    <li class="active nav-item me-2"><a class="nav-link" href="{% url 'app_home:swipe' %}">Swipe!</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item me-2"><a class="nav-link" href="{% url 'app_users:user-matches' %}">My
                            Matches</a></li>
                    {% endif %}
                    <li class="nav-item me-2"><a class="nav-link" href="{% url 'app_home:about' %}">About</a></li>

                    {% if request.user.is_authenticated %}
                    <li class="nav-item me-2 d-block d-sm-none"><a class="nav-link" href="/user/logout/">Sign Out</a>
                    </li>
                    <li class="nav-item me-2 d-block d-sm-none"><a class="nav-link"
                            href="{% url 'app_users:user-profile-details' %}">Profile</a></li>
                    {% else %}
                    <li class="nav-item me-2 d-block d-sm-none"><a class="nav-link" href="/user/login/">Sign In</a></li>
                    <li class="nav-item me-2 d-block d-sm-none"><a class="nav-link" href="/user/signup/">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <div class="d-none d-md-flex">
                {% if request.user.is_authenticated %}
                <p class="navbar-text my-auto me-2" style="padding: 20px;"><i>{{request.user.username.title}} is
                        Sockin'n'Rollin'!</i></p>
                <div class="dropdown" style="margin-right: 2em;">
                    <a href="#" data-bs-toggle="dropdown" class="dropdown-toggle" style="text-decoration: none;">
                        <img style="width: 80px; border-radius: 50%;" src="{{ request.user.get_picture_urls.0 }}">
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" style="font-size:120%;">
                        <li><a href="{% url 'app_users:user-profile-details' %}">My Profile</a></li>
                        <li><a href="{% url 'app_users:sock-overview' %}">My Socks</a></li>
                        <li><a href="{% url 'app_users:user-matches' %}">My Matches</a></li>
                        <li><a href="/user/logout/">Log out</a></li>
                    </ul>
                </div>
                {% else %}
                <p class="navbar-text my-auto me-2"><i>Wanna ramp up a sockin' life?</i></p>
                <div class="navbar">

                    <ul class="navbar-nav me-auto">
                        <li class="nav-item me-2"><a class="nav-link" href="/user/login/">Sign In</a></li>
                        <li class="nav-item me-2"><a class="nav-link" href="/user/signup/">Sign Up</a></li>
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>

    {% if messages %}
    <section>
        {% for msg in messages %}
        <!-- all django message tags mirror bootstrap, except error/danger -->
        <aside
            class="alert {% if msg.tags == 'error' %}alert-danger{% else %}alert-{{ msg.tags }}{% endif %} text-center alert-dismissible fade show"
            role="alert" style="backdrop-filter: None">
            <h4>{{ msg }}</h4>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> </button>
        </aside>
        {% endfor %}
    </section>
    {% endif %}

    {% block content %}{% endblock %}

    <footer></footer>
    <script src="https://kit.fontawesome.com/4a9fb983cf.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <!-- Bootstrap 5 import -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

django/templates/user_base.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1 offset-2">
            {% if left_arrow_go_to_url %}
            <a href="{{ left_arrow_go_to_url }}">
                <div class="arrow-container">
                    <img src="{% static 'left_arrow.png' %}" class="arrow" alt="">

                </div>
            </a>
            {% endif %}
        </div>

        <div class="col-xl-6 ">
            {% block user_content %}
            {% endblock %}
        </div>

        <div class="col-md-1">
            {% if right_arrow_go_to_url %}
            <a href="{{ right_arrow_go_to_url }}">
                <div class="arrow-container">
                    <img src="{% static 'right_arrow.png' %}" class="arrow" alt="">
                    <span>{% block right_arrow_content %} {% endblock %}</span>
                </div>
            </a>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}