django/app_chat/urls.py
from django.urls import path
from . import views


app_name = "app_chat"
urlpatterns = [path("<str:matched_user_name>", views.chat_with_match, name="chat")]

django/app_users/urls.py
from django.urls import path
from . import views

app_name = "app_users"
urlpatterns = [
    path("signup/", views.UserSignUp.as_view(), name="user-signup"),
    path(
        "profile/details/",
        views.UserProfileDetails.as_view(),
        name="user-profile-details",
    ),
    path(
        "profile/update/",
        views.UserProfileUpdate.as_view(),
        name="user-profile-update",
    ),
    path(
        "profile/delete/",
        views.UserProfileDelete.as_view(),
        name="user-profile-delete",
    ),
    path(
        "profile/picture/",
        views.UserProfilePictureUpdate.as_view(),
        name="user-profile-picture",
    ),
    path(
        "profile/matches/",
        views.UserMatches.as_view(),
        name="user-matches",
    ),
    path(
        "match/details/<str:username>/",
        views.UserMatchProfileDetails.as_view(),
        name="user-match-profile-details",
    ),
    path(
        "match/delete/<str:username>/",
        views.UserMatchDelete.as_view(),
        name="user-match-delete",
    ),
    path(
        "sock/overview/",
        views.SockProfileOverview.as_view(),
        name="sock-overview",
    ),
    path(
        "sock/select/",
        views.SockSelection.as_view(),
        name="sock-selection",
    ),
    path(
        "sock/details/",
        views.SockProfileDetails.as_view(),
        name="sock-details",
    ),
    path(
        "sock/create/",
        views.SockProfileCreate.as_view(),
        name="sock-create",
    ),
    path(
        "sock/update/",
        views.SockProfileUpdate.as_view(),
        name="sock-update",
    ),
    path(
        "sock/picture/",
        views.SockProfilePictureUpdate.as_view(),
        name="sock-picture",
    ),
]

django/hotsox_project/urls.py
import os
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    # Main Home route
    path("", include("app_home.urls")),
    # User Authentication
    path("user/", include("app_users.urls")),
    path("user/", include("allauth.urls")),
    path("chat/", include("app_chat.urls")),
    # API Routes
    path(os.environ.get("DRFAPI_URL", "api/v1") + "/", include("app_restapi.urls")),
    # path('api/auth/', include('rest_framework.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_URL)

django/app_users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.views.generic import TemplateView

from .validator import HotSoxLogInAndValidationCheckMixin, ProtectedSockMixin
from app_geo.utilities import GeoLocation, GeoMap
from .models import (
    User,
    UserProfilePicture,
    Sock,
    SockProfilePicture,
    UserMatch,
    MessageChat,
)
from .forms import (
    UserSignUpForm,
    UserProfileForm,
    UserProfilePictureForm,
    SockProfileForm,
    SockProfilePictureForm,
)

from allauth.account.views import SignupView
from app_mail.tasks import celery_send_mail


def validate_sock_ownership(request, valid_sock=None, picture_pk=None):
    # if picture is set
    if picture_pk:
        if int(picture_pk) in [picture.pk for picture in valid_sock.get_all_pictures()]:
            return True
        return False

    # if only sock object is set
    if valid_sock and valid_sock.user == request.user:
        return True

    return False


class UserSignUp(SignupView):
    """Custom UserSingUpView
    - add request object to the form
    - create user
    - add geolocation before saving to db (Using signals in models)
    """

    form_class = UserSignUpForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class UserProfileDetails(HotSoxLogInAndValidationCheckMixin, TemplateView):
    """View to show a user's details."""

    model = User
    template_name = "users/profile_details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # include the current user in the context
        user = get_object_or_404(User, pk=self.request.user.pk)
        context["user"] = user
        context["user_detail"] = user.to_json()

        # include the geo information in the context
        lat = user.location_latitude
        lng = user.location_longitude
        city = user.location_city
        if city and lat and lng:
            context["map"] = GeoMap.get_geo_map(
                map_width="100%",
                map_height="100%",
                geo_location_a=(lat, lng),
                geo_location_b=(lat, lng),
                city_location=city,
            )

        context["left_arrow_go_to_url"] = ""  # reverse("app_home:index")
        context["right_arrow_go_to_url"] = reverse("app_users:user-profile-update")
        return context


class UserProfileUpdate(LoginRequiredMixin, TemplateView):
    """View to edit details of a user.
    We will gather information from from.UserSignUpForm
    we  store this user to the db via ORM and try to
    login() then user!
    This View is not protected by the HotSoxLogInAndValidationCheckMixin!
    It needs to be available for users who are not validated!
    """

    model = User
    template_name = "users/profile_update.html"

    def post(self, request, *args, **kwargs):
        user_to_update = get_object_or_404(User, pk=request.user.pk)
        form_user_profile = UserProfileForm(request.POST, instance=user_to_update)

        if form_user_profile.is_valid():
            # update the user to the database
            user_to_update = form_user_profile.save(commit=False)
            # fix the data
            user_to_update.first_name = form_user_profile.cleaned_data[
                "first_name"
            ].title()
            user_to_update.last_name = form_user_profile.cleaned_data[
                "last_name"
            ].title()
            # set geo location
            try:
                (
                    user_to_update.location_latitude,
                    user_to_update.location_longitude,
                ) = GeoLocation.get_geolocation_from_city(user_to_update.location_city)
            except:
                user_to_update.location_latitude = 0
                user_to_update.location_longitude = 0
            # store the user to the database
            user_to_update.save()
            messages.success(request, "Profile details successfully updated.")
            # log user in via django login
            login(request, user_to_update)
            # redirect to user profile details page
            return redirect(reverse("app_users:user-profile-details"))
        # in case of invalid go here
        messages.warning(request, "Profile details could not be updated.")
        return render(
            request,
            "users/profile_update.html",
            {
                "form_user_profile": form_user_profile,
                "left_arrow_go_to_url": reverse("app_users:user-profile-details"),
                "right_arrow_go_to_url": reverse("app_users:sock-overview"),
            },
        )

    def get(self, request, *args, **kwargs):
        user_to_update = get_object_or_404(User, pk=request.user.pk)

        # get geo location from IP if not set
        if not user_to_update.location_city:
            try:
                city, _, _ = GeoLocation.get_geolocation_from_ip(
                    GeoLocation.get_ip_address(request)
                )
            except:
                city = {"city": ""}
            user_to_update.location_city = city["city"]

        form_user_profile = UserProfileForm(instance=user_to_update)

        # show user profile update page
        return render(
            request,
            "users/profile_update.html",
            {
                "form_user_profile": form_user_profile,
                "left_arrow_go_to_url": reverse("app_users:user-profile-details"),
                "right_arrow_go_to_url": reverse("app_users:sock-overview"),
            },
        )


class UserProfileDelete(HotSoxLogInAndValidationCheckMixin, TemplateView):
    """View to delete the user profile and all related details"""

    def get(self, request, *args, **kwargs):
        # get current user
        user = request.user
        # send email about account deletion
        celery_send_mail.delay(
            recipient_list=[user.email],
            notification=user.notification,
            email_subject="HotSox Account Deletion",
            email_message="Your HotSox account has been deleted. We are very sorry to see you go :(",
        )
        # delete user
        user.delete()
        # logout
        logout(request)
        # return to login site plus message
        messages.success(
            request, "Profile successfully deleted. Sorry to see you go :("
        )
        return redirect(reverse("account_login"))


class UserProfilePictureUpdate(HotSoxLogInAndValidationCheckMixin, TemplateView):
    """View to edit/add a new profile picture to a user."""

    model = User
    template_name = "users/profile_picture.html"

    def post(self, request, *args, **kwargs):
        # get current user
        user_to_update = get_object_or_404(User, pk=request.user.pk)
        # get all profile pictures from current user
        profile_picture_query_set = user_to_update.get_all_pictures()

        # check if profile_picture_query_set is not True
        if not profile_picture_query_set:
            profile_picture_query_set = [""]

        if request.POST.get("method") == "delete":
            # delete the selected picture!
            picture_pk = request.POST.get("picture_pk", None)
            if picture_pk:
                # validate that the picture_pk is part of the users profile pictures
                if int(picture_pk) in [
                    picture.pk for picture in request.user.get_all_pictures()
                ]:
                    UserProfilePicture_obj = UserProfilePicture.objects.get(
                        pk=picture_pk
                    )
                    UserProfilePicture_obj.delete()
                messages.success(request, "Profile picture successfully deleted.")
                return redirect(reverse("app_users:user-profile-picture"))

        elif request.POST.get("method") == "add":
            # add the selected picture!
            form_user_profile_picture = UserProfilePictureForm(
                request.POST,
                request.FILES,
                initial={"user": user_to_update},
            )
            if form_user_profile_picture.is_valid():
                # create a profile_picture object
                new_profile_picture = form_user_profile_picture.save(commit=False)
                # set one to many field [user] to current user
                new_profile_picture.user = user_to_update
                # store the picture to the database
                new_profile_picture.save()
                # redirect to user profile details page
                messages.success(request, "Profile picture successfully updated.")
                return redirect(reverse("app_users:user-profile-picture"))
            # in case of invalid go here
            messages.warning(request, "Profile picture could not be updated.")
            return redirect(reverse("app_users:user-profile-picture"))

    def get(self, request, *args, **kwargs):
        # get current user
        user_to_update = get_object_or_404(User, pk=request.user.pk)
        # get all profile pictures from current user
        profile_picture_query_set = user_to_update.get_all_pictures()
        # create form
        form_user_profile_picture = UserProfilePictureForm(
            initial={
                "user": user_to_update,
            },
        )

        # show user profile picture page
        return render(
            request,
            "users/profile_picture.html",
            {
                "profile_picture_query_set": profile_picture_query_set,
                "form_user_profile_picture": form_user_profile_picture,
                "left_arrow_go_to_url": "",

django/app_users/templates/users/match_profile_details.html
{% extends 'user_base.html' %}
{% block title %} Profile {% endblock %}
{% block user_content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h3>Your match {{user.username.title}}'s profile</h3>
            {% if user.get_picture_urls %}
            <div class="circle-container">
                {% for picture_url in user.get_picture_urls %}
                <div class="circle-img" id="profile-pic-{{ forloop.counter }}">
                    <img src="{{ picture_url }}" alt="">
                </div>
                {% endfor %}
            </div>
            {% else %}
            <p>No pictures available</p>
            {% endif %}
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            {% if user.first_name %}
            <span class="col-md-6" style="float:left; display:inline; word-wrap:break-word;">
                <strong>{{ user.first_name }}</strong>
            </span>
            {% else %}
            <span class="col-md-6" style="float:left; display:inline; word-wrap:break-word;">
                <strong>Anonymous Socker</strong>
            </span>
            {% endif %}
            <span class="col-md-6" style="float:right; display:inline; word-wrap:break-word;">
                {{ user_detail.age }} years old
            </span>
            <span class="col-md-6 style=" float:right; display:inline; word-wrap:break-word;"><strong>About</strong>
                <span class="col-md-6" style="float:right; display:inline; word-wrap:break-word;">
                    Lives in {{ user_detail.city }}, {{ distance }}km away
                </span>
            </span>

            <span class="col-md-12" style=" word-wrap:break-word;">
                <p>{{ user_detail.about }}</p>
            </span>

            <span class="col-md-6" style="float:left; display:inline; word-wrap:break-word;">
                {% if user_detail.instagram %}
                <a href="{{ user_detail.instagram }}" target="_blank"><i class="fa-brands fa-instagram"></i></a>
                {% endif %}
                {% if user_detail.facebook %}
                <a href="{{ user_detail.facebook }}" target="_blank"><i class="fa-brands fa-facebook"></i></a>
                {% endif %}
                {% if user_detail.twitter %}
                <a href="{{ user_detail.twitter }}" target="_blank"><i class="fa-brands fa-twitter"></i></a>
                {% endif %}
                {% if user_detail.spotify %}
                <a href="{{ user_detail.spotify }}" target="_blank"><i class="fa-brands fa-spotify"></i></a>
                {% endif %}
            </span>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <a href="{% url 'app_chat:chat' user_detail.username %}" class="btn btn-primary">Start a chat</a>
                <a href="{% url 'app_users:user-matches' %}" class="btn btn-primary">Back to matches</a>
            </div>
            <div class="col-md-1 offset-7">
                <button class="btn delete-button" data-bs-toggle="modal" data-bs-target="#deleteMatchModal"><i
                        class="fa-solid fa-trash-can"></i></a>
            </div>
        </div>
    </div>
    <br>
    <div class="col-md-12 card" style="padding: 15px">
        {{ map|safe }}
    </div>
</div>

<!-- The Modal -->
<div class="modal fade" id="deleteMatchModal" aria-labelledby="deleteMatchModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="deleteMatchModalLabel">You are about to unmatch
                    {{user_detail.username.title}} !</h4>
            </div>
            <div class="modal-body">You will not be able to chat with {{user_detail.username.title}} anymore. All the socks of this user will
                be hidden from you. Are you sure about this?
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-bs-dismiss="modal">Keep this match</button>
                <a href="{% url 'app_users:user-match-delete' user_detail.username %}" class="btn btn-danger"
                    id="confirm-delete">Delete this match</a>
            </div>
        </div>
    </div>
</div>

<!-- Rotate the user profile picture -->
<script>
    const pictures = document.querySelectorAll('.circle-img');
    // Hide all pictures at the beginning
    for (let i = 1; i < pictures.length; i++) {
        pictures[i].style.display = 'none';
    }
    function changePicture() {
        let pictures = document.querySelectorAll('.circle-img');
        let index = 0;
        setInterval(function () {
            pictures[index].style.display = 'none';
            index = (index + 1) % pictures.length;
            pictures[index].style.display = 'block';
        }, 5000);
    }
    changePicture();
</script>

{% endblock %}

django/app_users/templates/users/profile_details.html
{% extends 'user_base.html' %}
{% block title %} Profile {% endblock %}

{% block user_content %}

<h3>{{user.username.title}}'s Profile</h3>

{% if user.get_picture_urls %}
<div class="circle-container">
    {% for picture_url in user.get_picture_urls %}
    <div class="circle-img" id="profile-pic-{{ forloop.counter }}">
        <a href="{% url 'app_users:user-profile-picture' %}">
            <img src="{{ picture_url }}" alt="">
        </a>
    </div>
    {% endfor %}
</div>
{% else %}
<a href="{% url 'app_users:user-profile-picture' %}" class="btn">Add Picture</a>
{% endif %}

<div class="row">
    {% if user_detail.fullname %}
    <span class="col-md-6" style="float:left; display:inline; word-wrap:break-word;">
        <strong>{{ user_detail.fullname }}</strong>
    </span>
    {% else %}
    <span class="col-md-6" style="float:left; display:inline; word-wrap:break-word;">
        <strong>Anonymous Socker</strong>
    </span>
    {% endif %}
    <span class="col-md-6" style="float:right; display:inline; word-wrap:break-word;">
        <p>{{ user_detail.age }} years old</p>
    </span>
    <span class="col-md-6" style="float:left; display:inline; word-wrap:break-word;">
        <p>{{ user_detail.email }}</p>
    </span>
    <span class="col-md-6" style="float:right; display:inline; word-wrap:break-word;">
        <p>Lives in {{ user_detail.city }}</p>
    </span>
    <span class="col-md-6"><strong>About</strong></span>
    <span class="col-md-12" style=" word-wrap:break-word;">
        <p>{{ user_detail.about }}</p>
    </span>

    <span class="col-md-6" style="float:left; display:inline; word-wrap:break-word;">
        {% if user_detail.instagram %}
        <a href="{{ user_detail.instagram }}" target="_blank"><i class="fa-brands fa-instagram"></i></a>
        {% endif %}
        {% if user_detail.facebook %}
        <a href="{{ user_detail.facebook }}" target="_blank"><i class="fa-brands fa-facebook"></i></a>
        {% endif %}
        {% if user_detail.twitter %}
        <a href="{{ user_detail.twitter }}" target="_blank"><i class="fa-brands fa-twitter"></i></a>
        {% endif %}
        {% if user_detail.spotify %}
        <a href="{{ user_detail.spotify }}" target="_blank"><i class="fa-brands fa-spotify"></i></a>
        {% endif %}
    </span>
</div>

<div class="row">
    <div class="col-md-4 offset-4">
        <button class="btn delete-button" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i
            class="fa-solid fa-trash-can"></i> Delete Account</a>
    </div>
</div>

<br>
<div class="col-md-12 card" style="padding: 15px">
    {{ map|safe }}
</div>


    <!-- The Modal -->
    <div class="modal fade" id="deleteUserModal" aria-labelledby="deleteUserModalLabel">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="deleteUserModalLabel">You are about to delete your account
                        {{user.username.title}} !</h4>
                </div>
                <div class="modal-body">This action is irreversible. All your socks will
                    be deleted. Are you sure about this?
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" data-bs-dismiss="modal">Keep account</button>
                    <a href="{% url 'app_users:user-profile-delete' %}" class="btn btn-danger"
                        id="confirm-delete">Delete account</a>
                </div>
            </div>
        </div>
    </div>

<!-- Rotate the user profile picture -->
<script>
    const pictures = document.querySelectorAll('.circle-img');
    // Hide all pictures at the beginning
    for (let i = 1; i < pictures.length; i++) {
        pictures[i].style.display = 'none';
    }
    function changePicture() {
        let pictures = document.querySelectorAll('.circle-img');
        let index = 0;
        setInterval(function () {
            pictures[index].style.display = 'none';
            index = (index + 1) % pictures.length;
            pictures[index].style.display = 'block';
        }, 5000);
    }
    changePicture();
</script>

{% endblock %}

django/app_users/templates/users/profile_matches.html
{% extends 'user_base.html' %}
{% block title %} Matches {% endblock %}

{% block user_content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-4">
            <h2>{{user.username.title}}'s Matches</h2>
        </div>
        <div class="col-md-12 mt-3">
            {% if user_matches %}
            <p>Here is a list of your matches.</p>
            {% else %}
            <p>You do not currently have any matches :-(</p>
            <p>Click on swipe to swipe socks and increase your chances of finding a match!</p>
            {% endif %}
        </div>
    </div>

    <div class="row">
        {% if user_matches %}
        {% for match in user_matches %}
        <div class="col-md-6">
            <div class="card text-center h-100">
                {% if match.user == request.user %}
                {% if match.other.get_picture_urls %}
                <img src="{{match.other.get_picture_urls.0}}" alt="" class="circle-img">
                {% endif %}
                <div class="card-body card-center align-self-center" style="word-wrap:break-word">
                    <h5 class="card-title">{{ match.other.username.title }}</h5>
                    <div class="btn-group">
                        <a href="{% url 'app_users:user-match-profile-details' match.other.username %}"
                            class="btn btn-primary">View Profile</a>
                        <a href="{% url 'app_chat:chat' match.other.username %}" class="btn btn-primary">Chat</a>
                    </div>
                </div>
                {% else %}
                {% if match.user.get_picture_urls %}
                <img src="{{match.user.get_picture_urls.0}}" alt="" class="circle-img">
                {% endif %}
                <div class="card-body card-center align-self-center" style="word-wrap:break-word">
                    <h5 class="card-title">{{ match.user.username.title }}</h5>
                    <div class="btn-group">
                        <a href="{% url 'app_users:user-match-profile-details' match.user.username %}"
                            class="btn btn-primary">View Profile</a>
                        <a href="{% url 'app_chat:chat' match.user.username %}" class="btn btn-primary">Chat</a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>


{% endblock %}

django/app_users/templates/users/profile_update.html
{% extends "user_base.html" %}
{% load crispy_forms_tags %}
{% block title %} Update Profile {% endblock %}
{% block user_content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <h3>Revise/ edit {{user.username.title}}'s profile</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <form method="post" action="">
                {% csrf_token %}
                {{ form_user_profile|crispy }}
                <button class="btn" type="submit">Store profile</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

django/app_users/templates/users/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Signup {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <h3>Sign Up</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <form method="post" action="">
                {% csrf_token %}
                {{ form_user_profile|crispy }}
                <button class="btn btn-signup right" type="submit">Sign Up</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

django/app_users/templates/users/sock_details.html
{% extends "user_base.html" %}
{% block title %} {{ user.username.title }}'s sock - {{ sock.info_name }}' {% endblock %}
{% block user_content %}
<h3>{{sock.info_name.title}}'s Profile</h3>
<div class="circle-container">
    {% if sock.get_all_pictures.0 %}
    <div class="circle-img">
        <a href="{% url 'app_users:sock-picture' %}">
            <img src="{{ sock.get_picture_urls.0 }}" alt="">
        </a>
    </div>
    {% else %}
    <a href="{% url 'app_users:sock-picture' %}" class="btn">Add Picture</a>
    {% endif %}
</div>

<div class="row">
    <div class="col-md">
        {% for key, value in sock.to_json.items %}
        {% if value %}
        <p><strong>{{ key }}:</strong> {{ value }}</p>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

django/app_users/templates/users/sock_overview.html
{% extends "user_base.html" %}
{% block title %} {{ user.username.title }}'s socks' {% endblock %}
{% block user_content %}

<div class="row">
    <div class="col-md-8 mt-3 offset-md-4">
        <h2>Sock Overview</h2>
    </div>
    <div class="col-md-12 mt-3">
        {% if user.get_socks %}
        <p>Here is an overview of all your socks. Click on one to select it as your active sock and to see more details,
            or click on the + button to add a new sock.</p>
        {% else %}
        <p>You do not currently have any socks. Click on the + button below to add one!</p>
        {% endif %}
    </div>
</div>

<div class="row">
    {% for sock in user.get_socks %}
    {% if sock %}
    <div class="col-3">
        <div class="card text-center">
            {% if sock.get_picture_urls.0 %}
            <form action="{% url 'app_users:sock-selection' %}" method="POST">
                {% csrf_token %}
                <button class="btn-img-hide">
                    <input type="hidden" name="sock_pk" value="{{sock.pk}}">
                    <input type="hidden" name="redirect_url" value="{% url 'app_users:sock-details' %}">
                    <img src="{{sock.get_picture_urls.0}}" alt="" class="card-img-top">
                </button>
                <br>
                <br>
                <p>{{sock.info_name}}</p>
            </form>
            {% else %}
            <div class="card-body card-center align-self-center">
                <form action="{% url 'app_users:sock-selection' %}" method="POST">
                    {% csrf_token %}
                    <button class="plus-btn"><i class="fa-solid fa-plus"></i></button>
                    <input type="hidden" name="sock_pk" value="{{sock.pk}}">
                    <input type="hidden" name="redirect_url" value="{% url 'app_users:sock-picture' %}">
                    <p>{{sock.info_name}}</p>
                </form>
            </div>
            {% endif %}
            <div class="card-body">
                <button class="btn card-btn delete-button" data-bs-toggle="modal"
                    data-bs-target="#deleteSockModal-{{ sock.pk }}"><i class="fa-solid fa-trash-can"></i></button>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="modal fade" id="deleteSockModal-{{ sock.pk }}" aria-labelledby="deleteSockModalLabel">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="deleteSockModalLabel">Deleting a sock is irreversible!</h4>
                </div>
                <div class="modal-body">Your are about to delete all information,
                    all photos and matches for this sock. Are you really sure you want to proceed?</div>
                <div class="modal-footer">
                    <button class="btn btn-primary" data-bs-dismiss="modal">Keep this sock</button>
                    <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="method" value="delete">
                        <input type="hidden" name="sock_pk" value="{{sock.pk}}">
                        <button class="btn delete-button">Delete this sock</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="col-3">
        <div class="card text-center">
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="method" value="add">
                <button class="plus-btn"><i class="fa-solid fa-plus"></i></button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

django/app_users/templates/users/sock_update.html
{% extends "user_base.html" %}
{% block title %} {{ user.username.title }}'s sock - {{ sock.info_name }}' {% endblock %}
{% load crispy_forms_tags %}
{% block user_content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            {% if sock %}
            <h3>Edit {{sock.info_name.title}}'s profile</h3>
            {% else %}
            <h3>Add a new sock!</h3>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <form method="post" action="">
                {% csrf_token %}
                {{ form_sock_profile|crispy }}
                <button class="btn" type="submit">Store profile</button>
            </form>

        </div>
    </div>
</div>
{% endblock %}